// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2BGADhlrbxgN6V_rpajj6O8r4TNjKtXk',
    appId: '1:981372119934:web:02436719ef9dc7db61212f',
    messagingSenderId: '981372119934',
    projectId: 'chatapptute-d3314',
    authDomain: 'chatapptute-d3314.firebaseapp.com',
    storageBucket: 'chatapptute-d3314.appspot.com',
    measurementId: 'G-TCGVE7E752',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUfXp9QJbsZgYyfTT_PBQB0C2Y19FLyeM',
    appId: '1:981372119934:android:8d540ef0245e616f61212f',
    messagingSenderId: '981372119934',
    projectId: 'chatapptute-d3314',
    storageBucket: 'chatapptute-d3314.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_MayqpLmYzyF8frIawmbU6xcDkSJLRLM',
    appId: '1:981372119934:ios:bb1e23c7c4d6481f61212f',
    messagingSenderId: '981372119934',
    projectId: 'chatapptute-d3314',
    storageBucket: 'chatapptute-d3314.appspot.com',
    iosBundleId: 'com.example.chatappFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_MayqpLmYzyF8frIawmbU6xcDkSJLRLM',
    appId: '1:981372119934:ios:f3d3ba468465a4ed61212f',
    messagingSenderId: '981372119934',
    projectId: 'chatapptute-d3314',
    storageBucket: 'chatapptute-d3314.appspot.com',
    iosBundleId: 'com.example.chatappFlutter.RunnerTests',
  );
}
